### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by ChaseHamby** [nss-evening-cohort-8/chatty-kleenex#20]
# User Story
As a developer, when I clone the repo, I should see some boilerplate code.

# Acceptance Criteria
When the user visits the page, they should see a white background color with an empty input text box in the center.

# Tech Notes
° index.html - boilerplate code with an empty print div
° main.css - put a box around the div
° Javascripts folder
° Javascripts / main.js - initializeApp function - console.log
° js events folder - console.log
° js/events/eventlisteners.js - console.log
° js/helpers/util.js - console.log
° js database folder
° js/db/json file
° js data folder
° js/data/xhr file
° script tags for all JS files
° bootstrap 4

**Comment by meeshysu** [comment]
![chatty](https://user-images.githubusercontent.com/41173019/46642518-6142a000-cb3d-11e8-816b-2dcdbfc3b860.png)
